# Generated by Django 2.2.5 on 2019-09-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='numberOfPages',
            new_name='number_of_pages',
        ),
    ]
