# Generated by Django 2.2.5 on 2019-09-26 05:19

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0002_auto_20190923_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
